export type Language = 'ru' | 'kk' | 'en';

const ru = {
  loading: 'Загрузка Forest Base…', guestName: 'Гость', tagline: 'Переживи ночь. Защити крепость.', explore: 'Исследуй большой лес', supplies: 'Собирай припасы', fight: 'Отбивайся от зомби',
  language: 'Язык', sound: 'Громкость', signup: 'Регистрация', signin: 'Вход', nickname: 'Никнейм', nicknameHint: 'Имя над персонажем', email: 'Адрес почты', password: 'Пароль', passwordHint: 'Минимум 6 символов', repeatPassword: 'Повтори пароль', repeatHint: 'Введи пароль ещё раз', wait: 'Подождите…', create: 'Создать аккаунт', enter: 'Войти в игру', or: 'или', google: 'Продолжить через Google', guest: 'Войти как гость',
  chooseDifficulty: 'Выбери сложность', rookieInfo: 'Короткое выживание для знакомства с лесом.', survivorInfo: 'Больше волн и меньше времени на ошибки.', nightmareInfo: 'Долгая борьба за каждый ресурс.', nights: 'ночей', goal: 'Продержись {count} ночей', day: 'День', night: 'Ночь', base: 'База', health: 'Здоровье', inventory: 'Инвентарь', close: 'Закрыть', wood: 'Дерево', food: 'Еда', water: 'Вода', eat: 'Съесть', drink: 'Выпить', inventoryHint: 'B — инвентарь', inventoryHelp: 'F — построить забор за 2 дерева. B или Escape — закрыть.', controls: 'WASD — движение · E — взаимодействие · ЛКМ — атака · ПКМ — ремонт · F — забор', startNight: 'Начать ночь', wave: 'Волна идёт…', restart: 'Начать заново',
  survived: 'Спасатели прибыли', survivedNights: 'Ты пережил {count} ночей!', time: 'Время прохождения', playAgain: 'Сыграть ещё раз', ended: 'Выживание окончено', defeat: 'ПОРАЖЕНИЕ', tryAgain: 'Попробовать снова', warehouse: 'СКЛАД',
};

export type TranslationKey = keyof typeof ru;
const kk: Record<TranslationKey, string> = {
  loading: 'Forest Base жүктелуде…', guestName: 'Қонақ', tagline: 'Түннен аман өт. Қамалды қорға.', explore: 'Үлкен орманды зертте', supplies: 'Қор жина', fight: 'Зомбилермен шайқас', language: 'Тіл', sound: 'Дыбыс', signup: 'Тіркелу', signin: 'Кіру', nickname: 'Лақап ат', nicknameHint: 'Кейіпкер үстіндегі ат', email: 'Электрондық пошта', password: 'Құпиясөз', passwordHint: 'Кемінде 6 таңба', repeatPassword: 'Құпиясөзді қайтала', repeatHint: 'Құпиясөзді қайта енгіз', wait: 'Күте тұрыңыз…', create: 'Аккаунт ашу', enter: 'Ойынға кіру', or: 'немесе', google: 'Google арқылы жалғастыру', guest: 'Қонақ ретінде кіру', chooseDifficulty: 'Қиындықты таңда', rookieInfo: 'Орманмен танысуға арналған қысқа ойын.', survivorInfo: 'Толқын көп, қателесуге уақыт аз.', nightmareInfo: 'Әр ресурс үшін ұзақ күрес.', nights: 'түн', goal: '{count} түн шыда', day: 'Күн', night: 'Түн', base: 'Қамал', health: 'Денсаулық', inventory: 'Қоржын', close: 'Жабу', wood: 'Ағаш', food: 'Тамақ', water: 'Су', eat: 'Жеу', drink: 'Ішу', inventoryHint: 'B — қоржын', inventoryHelp: 'F — 2 ағашқа қоршау салу. B немесе Escape — жабу.', controls: 'WASD — қозғалу · E — әрекет · СЖБ — шабуыл · ОЖБ — жөндеу · F — қоршау', startNight: 'Түнді бастау', wave: 'Шабуыл жүріп жатыр…', restart: 'Қайта бастау', survived: 'Құтқарушылар келді', survivedNights: 'Сен {count} түннен аман өттің!', time: 'Өту уақыты', playAgain: 'Қайта ойнау', ended: 'Аман қалу аяқталды', defeat: 'ЖЕҢІЛІС', tryAgain: 'Қайта көру', warehouse: 'ҚОЙМА',
};
const en: Record<TranslationKey, string> = {
  loading: 'Loading Forest Base…', guestName: 'Guest', tagline: 'Survive the night. Defend the fortress.', explore: 'Explore the vast forest', supplies: 'Gather supplies', fight: 'Fight off zombies', language: 'Language', sound: 'Volume', signup: 'Sign up', signin: 'Sign in', nickname: 'Nickname', nicknameHint: 'Name above your character', email: 'Email address', password: 'Password', passwordHint: 'At least 6 characters', repeatPassword: 'Repeat password', repeatHint: 'Enter the password again', wait: 'Please wait…', create: 'Create account', enter: 'Enter game', or: 'or', google: 'Continue with Google', guest: 'Play as guest', chooseDifficulty: 'Choose difficulty', rookieInfo: 'A short survival run to learn the forest.', survivorInfo: 'More waves and less room for mistakes.', nightmareInfo: 'A long fight for every resource.', nights: 'nights', goal: 'Survive {count} nights', day: 'Day', night: 'Night', base: 'Base', health: 'Health', inventory: 'Inventory', close: 'Close', wood: 'Wood', food: 'Food', water: 'Water', eat: 'Eat', drink: 'Drink', inventoryHint: 'B — inventory', inventoryHelp: 'F — build a fence for 2 wood. B or Escape — close.', controls: 'WASD — move · E — interact · LMB — attack · RMB — repair · F — fence', startNight: 'Start night', wave: 'Wave in progress…', restart: 'Restart', survived: 'Rescuers arrived', survivedNights: 'You survived {count} nights!', time: 'Completion time', playAgain: 'Play again', ended: 'Survival ended', defeat: 'DEFEAT', tryAgain: 'Try again', warehouse: 'STORAGE',
};
export const translations = { ru, kk, en };
